
// This code was auto-generated by xRegistry CLI

// This code was generated by the xRegistry tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#nullable enable

using System;
using System.IO;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Threading;
using Azure;
using Azure.Core;
using Azure.Messaging.EventHubs;
using Azure.Messaging.EventHubs.Processor;
using Azure.Messaging.EventHubs.Producer;
using Azure.Storage.Blobs;
using Xunit;
using Microsoft.Extensions.Logging;
using Testcontainers.Azurite;
using DotNet.Testcontainers.Containers;
using DotNet.Testcontainers.Builders;
using DotNet.Testcontainers.Networks;

using Vasters.ForzaBridge.Producer;
using Vasters.ForzaBridge.Producer.ForzaMotorsport.Telemetry;
using CloudNative.CloudEvents;
using CloudNative.CloudEvents.SystemTextJson;

namespace Vasters.ForzaBridge.Producer.Test
{
    public class VastersForzaBridgeProducerFixture : IAsyncLifetime
    {
        public AzuriteContainer? AzuriteContainer { get; protected set; }
        public IContainer? EmulatorContainer { get; protected set; }
        public INetwork? Network { get; protected set; }
        public string? EventHubConnectionString { get; protected set; }
        public string? BlobStorageConnectionString { get; protected set; }
        public BlobContainerClient? BlobClient { get; protected set; }
        private ILoggerFactory _loggerFactory;
        private ILogger _logger;

        public ILoggerFactory GetLoggerFactory()
        {
            return _loggerFactory;
        }

        private string? emulatorConfigFilePath = null;
        private const string emulatorConfig = @"{
                      ""UserConfig"": {
                        ""NamespaceConfig"": [
                          {
                            ""Type"": ""EventHub"",
                            ""Name"": ""emulatorNs1"",
                            ""Entities"": [
                              {
                                ""Name"": ""eh1"",
                                ""PartitionCount"": ""2"",
                                ""ConsumerGroups"": [
                                  {
                                    ""Name"": ""cg1""
                                  }
                                ]
                              }
                            ]
                          }
                        ], 
                        ""LoggingConfig"": {
                          ""Type"": ""File""
                        }
                      }
                    }";

        public VastersForzaBridgeProducerFixture()
        {
            _loggerFactory = LoggerFactory.Create(builder =>
            {
                builder.AddDebug().AddConsole();
            });
            _logger = _loggerFactory.CreateLogger<VastersForzaBridgeProducerFixture>();
        }

        public async Task InitializeAsync()
        {
            try
            {
                Network = new NetworkBuilder()
                    .WithName(Guid.NewGuid().ToString("D"))
                    .Build();
                emulatorConfigFilePath = Path.GetTempFileName();
                File.WriteAllText(emulatorConfigFilePath, emulatorConfig);  
                AzuriteContainer = new AzuriteBuilder()
                    .WithImage("mcr.microsoft.com/azure-storage/azurite:latest")
                    .WithCommand("--skipApiVersionCheck")
                    .WithNetwork(Network)
                    .WithNetworkAliases("azurite")
                    .WithWaitStrategy(Wait.ForUnixContainer().UntilMessageIsLogged(".*Azurite Blob service is successfully listening"))
                    .Build();
                
                EmulatorContainer = new ContainerBuilder()
                        .WithImage("mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest")
                        .WithBindMount(emulatorConfigFilePath,"/Eventhubs_Emulator/ConfigFiles/Config.json")
                        .WithPortBinding(5672, false)
                        .WithNetwork(Network)
                        .WithNetworkAliases("eventhubs-emulator")
                        .WithEnvironment("BLOB_SERVER", "azurite")
                        .WithEnvironment("METADATA_SERVER", "azurite")
                        .WithEnvironment("ACCEPT_EULA", "Y")
                        .WithWaitStrategy(Wait.ForUnixContainer().UntilMessageIsLogged(".*Emulator is launching with config"))
                        .Build();

                await Network.CreateAsync();
                await AzuriteContainer.StartAsync();
                await EmulatorContainer.StartAsync();
                EventHubConnectionString = $"Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;EntityPath=eh1;";
                BlobStorageConnectionString = AzuriteContainer.GetConnectionString();
                BlobClient = new BlobContainerClient(BlobStorageConnectionString, "eventhub-checkpoints");
                if ( !await BlobClient.ExistsAsync())
                {
                    await BlobClient.CreateAsync();
                    if ( !await BlobClient.ExistsAsync())
                    {
                        throw new Exception("Blob container not created");
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred during InitializeAsync");
                throw;
            }
        }

        public async Task DisposeAsync()
        {
            try
            {
                if (EmulatorContainer != null)
                {
                    await EmulatorContainer.StopAsync();
                }
                if (AzuriteContainer != null)
                {
                    await AzuriteContainer.StopAsync();
                }
                if (Network != null)
                {
                    await Network.DeleteAsync();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred during DisposeAsync: {ex.Message}");
            }
            finally
            {
                if (emulatorConfigFilePath != null && File.Exists(emulatorConfigFilePath))
                {
                    File.Delete(emulatorConfigFilePath);
                }
            }
        }
    }

    [CollectionDefinition("EventHubs emulator")]
    public class VastersForzaBridgeProducerCollectionFixture : ICollectionFixture<VastersForzaBridgeProducerFixture>
    {
    }
    [Collection("EventHubs emulator")]
    public class VastersForzaBridgeProducerForzaMotorsportTelemetryProducerTests 
    {
        private readonly VastersForzaBridgeProducerFixture _fixture;
        private readonly ILogger _logger;
        private readonly global::Vasters.ForzaBridge.Producer.ForzaMotorsport.Telemetry.TelemetryProducer _producer;

        public VastersForzaBridgeProducerForzaMotorsportTelemetryProducerTests(VastersForzaBridgeProducerFixture fixture)
        {
            _fixture = fixture;
            _logger = _fixture.GetLoggerFactory().CreateLogger<VastersForzaBridgeProducerForzaMotorsportTelemetryProducerTests>();
            var eventHubClient = new EventHubProducerClient(_fixture.EventHubConnectionString);
            _producer = new global::Vasters.ForzaBridge.Producer.ForzaMotorsport.Telemetry.TelemetryProducer(eventHubClient);
        }

#pragma warning disable CS8604 // init takes care of nullables
        [Fact]
        public async Task TestChannelMessage()
        {
            _logger.LogInformation("Starting TestChannelMessage");
            try
            {
                var eventDataTest = new global::Vasters.ForzaBridge.ProducerData.ForzaMotorsport.Telemetry.ChannelTests();
                var eventDataInstance = eventDataTest.CreateInstance();
                await _producer.SendChannelAsync(eventDataInstance, tenantid: "test", carId: "test", channelId: "test");
                _logger.LogInformation("Test event sent");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred during TestChannelMessage");
                throw;
            }
        }

        [Fact]
        public async Task TestChannelBatch()
        {
            _logger.LogInformation("Starting TestChannelBatch");
            try
            {
                var eventDataTest = new global::Vasters.ForzaBridge.ProducerData.ForzaMotorsport.Telemetry.ChannelTests();
                var eventDataInstances = new global::Vasters.ForzaBridge.ProducerData.ForzaMotorsport.Telemetry.Channel[10];
                for (int i = 0; i < 10; i++)
                {
                    eventDataInstances[i] = eventDataTest.CreateInstance();
                }
                await _producer.SendChannelBatchAsync(eventDataInstances, tenantid:"test", carId:"test", channelId:"test");
                _logger.LogInformation("Test batch event sent");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred during TestChannelBatch");
                throw;
            }
        }
        [Fact]
        public async Task TestLapSignalMessage()
        {
            _logger.LogInformation("Starting TestLapSignalMessage");
            try
            {
                var eventDataTest = new global::Vasters.ForzaBridge.ProducerData.ForzaMotorsport.Telemetry.LapSignalTests();
                var eventDataInstance = eventDataTest.CreateInstance();
                await _producer.SendLapSignalAsync(eventDataInstance, tenantid: "test", carId: "test", sessionId: "test");
                _logger.LogInformation("Test event sent");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred during TestLapSignalMessage");
                throw;
            }
        }

        [Fact]
        public async Task TestLapSignalBatch()
        {
            _logger.LogInformation("Starting TestLapSignalBatch");
            try
            {
                var eventDataTest = new global::Vasters.ForzaBridge.ProducerData.ForzaMotorsport.Telemetry.LapSignalTests();
                var eventDataInstances = new global::Vasters.ForzaBridge.ProducerData.ForzaMotorsport.Telemetry.LapSignal[10];
                for (int i = 0; i < 10; i++)
                {
                    eventDataInstances[i] = eventDataTest.CreateInstance();
                }
                await _producer.SendLapSignalBatchAsync(eventDataInstances, tenantid:"test", carId:"test", sessionId:"test");
                _logger.LogInformation("Test batch event sent");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred during TestLapSignalBatch");
                throw;
            }
        }
    }
}